# yt-app/.github/workflows/ping-backend.yml

name: Keep Backend Warm (Twice Daily Ping)

on:
  schedule:
    - cron: '0 3 * * *'   # 3:00 AM UTC
    - cron: '0 15 * * *'  # 3:00 PM UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Curl health endpoint
        run: curl -s https://vidsync-be.onrender.com/api/healthz
