# yt-app/.github/workflows/ping-backend.yml

name: Keep Backend Warm (Every 5 Hours Ping)

on:
  schedule:
    - cron: '0 0 * * *'   # 12:00 AM UTC
    - cron: '0 5 * * *'   # 5:00 AM UTC
    - cron: '0 10 * * *'  # 10:00 AM UTC
    - cron: '0 15 * * *'  # 3:00 PM UTC
    - cron: '0 20 * * *'  # 8:00 PM UTC
  workflow_dispatch:      # manual trigger support

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Curl health endpoint
        run: curl -s https://vidsync-be.onrender.com/api/healthz